//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliPayIPN
    {
        public long PaymentId { get; set; }
        public string notify_time { get; set; }
        public string notify_type { get; set; }
        public string notify_id { get; set; }
        public string sign_type { get; set; }
        public string sign { get; set; }
        public string out_trade_no { get; set; }
        public string subject { get; set; }
        public string payment_type { get; set; }
        public string trade_no { get; set; }
        public string trade_status { get; set; }
        public string seller_id { get; set; }
        public string seller_email { get; set; }
        public string buyer_id { get; set; }
        public string buyer_email { get; set; }
        public string total_fee { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
        public string body { get; set; }
        public string gmt_create { get; set; }
        public string gmt_payment { get; set; }
        public string is_total_fee_adjust { get; set; }
        public string use_coupon { get; set; }
        public string discount { get; set; }
        public string refund_status { get; set; }
        public string gmt_refund { get; set; }
        public string gmt_close { get; set; }
        public string extra_common_param { get; set; }
        public string out_channel_type { get; set; }
        public string out_channel_amount { get; set; }
        public string out_channel_inst { get; set; }
        public string business_scene { get; set; }
        public string note { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
