//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow
    {
        public long CashFlowId { get; set; }
        public long UserId { get; set; }
        public long UserTypeId { get; set; }
        public int TradeTypeId { get; set; }
        public string CashFlowNumber { get; set; }
        public string ExternalCashFlowNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public Nullable<long> TradeId { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public string Note { get; set; }
        public Nullable<int> CashFlowStatusId { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public string ReviewNote { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CashFlowStatu CashFlowStatu { get; set; }
        public virtual Trade Trade { get; set; }
    }
}
