//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassCource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassCource()
        {
            this.StudentClassCources = new HashSet<StudentClassCource>();
        }
    
        public int ClassCourceId { get; set; }
        public int TeacherId { get; set; }
        public string ClassId { get; set; }
        public string Title { get; set; }
        public System.DateTime Create_Time { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public string TeacherPassword { get; set; }
        public string StudentPassword { get; set; }
        public string TeacherClassId { get; set; }
        public Nullable<System.DateTime> TeacherJoinTime { get; set; }
        public string TeacherClassUrl { get; set; }
        public string File_Ids { get; set; }
        public string TeacherPlayBackAddress { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassCource> StudentClassCources { get; set; }
    }
}
