//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fav
    {
        public int FavId { get; set; }
        public Nullable<int> PublicCourceId { get; set; }
        public Nullable<int> BBSDetailId { get; set; }
        public int StudentId { get; set; }
    
        public virtual BBSDetail BBSDetail { get; set; }
        public virtual PublicCource PublicCource { get; set; }
        public virtual Student Student { get; set; }
    }
}
