//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.StudentClassCources = new HashSet<StudentClassCource>();
        }
    
        public int OrderId { get; set; }
        public int CourcePkgId { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> Pay_Time { get; set; }
        public Nullable<System.DateTime> Expired_Time { get; set; }
        public System.DateTime Create_Time { get; set; }
        public decimal Cost { get; set; }
        public bool Status { get; set; }
    
        public virtual CourcePkg CourcePkg { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassCource> StudentClassCources { get; set; }
    }
}
