//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string QQ { get; set; }
        public string RealName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool Sex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public string Code { get; set; }
        public System.DateTime CodeSendTime { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime Data_CreateTime { get; set; }
    }
}
