//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKHY.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trade()
        {
            this.CashFlows = new HashSet<CashFlow>();
        }
    
        public long TradeId { get; set; }
        public int TradeTypeId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public long UserId { get; set; }
        public int UserTypeId { get; set; }
        public decimal Topup { get; set; }
        public decimal Payment { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DatePaymentConfirmed { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashFlow> CashFlows { get; set; }
        public virtual TradeType TradeType { get; set; }
    }
}
